apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  selector:
    matchLabels:
      app: my-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: app
          image:  gcr.to/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
