apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  selector:
    matchLabels:
      app: my-node-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image:  gcr.io/sit727-23t1-singh-99b19b1/my-node-app
          ports:
            - containerPort: 5000
