apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  selector:
    matchLabels:
      app: my-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image:  mukulksingh98/sit737:latest
          ports:
            - containerPort: 5000
